version: "3"
services:
  stories:
    image: "story-app:1"
    # image: story-app
    build: .
    volumes:
      - stories:/app/story
    ports:
      - 8018:3000
    environment:
      - STORY_FOLDER=story
volumes:
  stories:
