apiVersion: v1
kind: Service
metadata:
  name: second-app-service
spec:
  selector:
    app: second-app
    tier: backend
  ports:
    - protocol: TCP
      port: 80         # outer port
      targetPort: 8080 # container port
  type: LoadBalancer # ClusterIP . NodePort . LoadBalancer
